### ISSUE TITLE
Bug in Tiddit when using alt-contigs

### ISSUE THREAD

**Issue by SarahBeecroft** [Sydney-Informatics-Hub/Germline-StructuralV-nf#20]
Some samples will fail when using alt-contigs (as opposed to just chromosomes) with the Tiddit-sc step. The specific error I found:

```
Traceback (most recent call last):
    File "/usr/local/bin/tiddit", line 11, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.9/site-packages/tiddit/__main__.py", line 151, in main
      tiddit_contig_analysis.main(prefix,sample_id,library,contigs,coverage_data,args)
    File "tiddit/tiddit_contig_analysis.pyx", line 133, in tiddit.tiddit_contig_analysis.main
    File "tiddit/tiddit_contig_analysis.pyx", line 57, in tiddit.tiddit_contig_analysis.read_contigs
  KeyError: 'HLADRB1*04:03:01'
```

It looks like there might be some parsing error, because this should be formatted as HLA-DRB1*04:03:01 (i.e. it's missing a dash). For testing purposes I've added `errorStrategy 'ignore'` to the tiddit-sv module file so the pipeline can keep going. The failed sample was Platinum genome ERR194159, using the fasta reference from Sarek iGenome `Homo_sapiens_assembly38.fasta`.

**Comment by georgiesamaha** [comment]
Adding reported issue @ Tiddit https://github.com/SciLifeLab/TIDDIT/issues/103

**Comment by georgiesamaha** [comment]
Resolved
